services:
  docker-dind:
    image: docker:dind
    container_name: docker-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    ports:
      - "2375:2375"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-net

  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://docker-dind:2375
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-net

networks:
  jenkins-net:

volumes:
  jenkins_home:
    external: true
    name: jenkins_home
